android.useAndroidX=true
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=35
org.gradle.jvmargs=-Xmx4096m --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED
org.gradle.caching=true

# Project SDK config (read by build scripts)
compileSdk=35
targetSdk=35
minSdk=28
